export interface CatalogMarket {
  country: string;
  timezone: string;
  exchanges: string;
  currency: string;
  sessions: readonly { open: string; close: string }[];
  weekdays: readonly number[];
  suffixes: readonly { suffix: string; exchange: string; mic: string }[];
  testSymbol: string;
  holidayCalendar: string;
}

const MON_FRI = [1, 2, 3, 4, 5] as const;
const SUN_THU = [0, 1, 2, 3, 4] as const;
const day = (open: string, close: string) => [{ open, close }];
const split = (open: string, lunch: string, back: string, close: string) => [
  { open, close: lunch },
  { open: back, close },
];

export const MARKET_CATALOG: readonly CatalogMarket[] = [
  {
    country: 'US',
    timezone: 'America/New_York',
    exchanges: 'NYSE, Nasdaq',
    currency: 'USD',
    sessions: day('09:30', '16:00'),
    weekdays: MON_FRI,
    suffixes: [],
    testSymbol: 'SPY',
    holidayCalendar: 'usa',
  },
  {
    country: 'CA',
    timezone: 'America/Toronto',
    exchanges: 'TSX, TSXV, Cboe Canada',
    currency: 'CAD',
    sessions: day('09:30', '16:00'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'TO', exchange: 'TSX', mic: 'XTSE' },
      { suffix: 'V', exchange: 'TSXV', mic: 'XTSX' },
      { suffix: 'NE', exchange: 'NEO', mic: 'NEOE' },
    ],
    testSymbol: 'RY.TO',
    holidayCalendar: 'canadian',
  },
  {
    country: 'MX',
    timezone: 'America/Mexico_City',
    exchanges: 'BMV',
    currency: 'MXN',
    sessions: day('08:30', '15:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'MX', exchange: 'BMV', mic: 'XMEX' }],
    testSymbol: 'WALMEX.MX',
    holidayCalendar: 'mexican',
  },
  {
    country: 'BR',
    timezone: 'America/Sao_Paulo',
    exchanges: 'B3',
    currency: 'BRL',
    sessions: day('10:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'SA', exchange: 'B3', mic: 'BVMF' }],
    testSymbol: 'PETR4.SA',
    holidayCalendar: 'brazilian',
  },
  {
    country: 'AR',
    timezone: 'America/Argentina/Buenos_Aires',
    exchanges: 'BYMA',
    currency: 'ARS',
    sessions: day('11:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'BA', exchange: 'BYMA', mic: 'XBUE' }],
    testSymbol: 'GGAL.BA',
    holidayCalendar: 'ar',
  },
  {
    country: 'CL',
    timezone: 'America/Santiago',
    exchanges: 'Bolsa de Santiago',
    currency: 'CLP',
    sessions: day('09:30', '16:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'SN', exchange: 'BCS', mic: 'XSGO' }],
    testSymbol: 'COPEC.SN',
    holidayCalendar: 'cl',
  },
  {
    country: 'GB',
    timezone: 'Europe/London',
    exchanges: 'LSE',
    currency: 'GBP',
    sessions: day('08:00', '16:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'L', exchange: 'LSE', mic: 'XLON' }],
    testSymbol: 'VOD.L',
    holidayCalendar: 'uk',
  },
  {
    country: 'IE',
    timezone: 'Europe/Dublin',
    exchanges: 'Euronext Dublin',
    currency: 'EUR',
    sessions: day('08:00', '16:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'IR', exchange: 'Euronext Dublin', mic: 'XMSM' }],
    testSymbol: 'RYA.IR',
    holidayCalendar: 'irish',
  },
  {
    country: 'FR',
    timezone: 'Europe/Paris',
    exchanges: 'Euronext Paris',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'PA', exchange: 'Euronext Paris', mic: 'XPAR' }],
    testSymbol: 'MC.PA',
    holidayCalendar: 'french',
  },
  {
    country: 'NL',
    timezone: 'Europe/Amsterdam',
    exchanges: 'Euronext Amsterdam',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'AS', exchange: 'Euronext Amsterdam', mic: 'XAMS' }],
    testSymbol: 'ASML.AS',
    holidayCalendar: 'dutch',
  },
  {
    country: 'BE',
    timezone: 'Europe/Brussels',
    exchanges: 'Euronext Brussels',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'BR', exchange: 'Euronext Brussels', mic: 'XBRU' }],
    testSymbol: 'ABI.BR',
    holidayCalendar: 'be',
  },
  {
    country: 'DE',
    timezone: 'Europe/Berlin',
    exchanges: 'Xetra, Börse Frankfurt',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'DE', exchange: 'Xetra', mic: 'XETR' },
      { suffix: 'F', exchange: 'Börse Frankfurt', mic: 'XFRA' },
    ],
    testSymbol: 'SAP.DE',
    holidayCalendar: 'german',
  },
  {
    country: 'CH',
    timezone: 'Europe/Zurich',
    exchanges: 'SIX',
    currency: 'CHF',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'SW', exchange: 'SIX', mic: 'XSWX' }],
    testSymbol: 'NESN.SW',
    holidayCalendar: 'ch',
  },
  {
    country: 'ES',
    timezone: 'Europe/Madrid',
    exchanges: 'BME',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'MC', exchange: 'BME', mic: 'XMAD' }],
    testSymbol: 'SAN.MC',
    holidayCalendar: 'spain',
  },
  {
    country: 'IT',
    timezone: 'Europe/Rome',
    exchanges: 'Borsa Italiana',
    currency: 'EUR',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'MI', exchange: 'Borsa Italiana', mic: 'XMIL' }],
    testSymbol: 'ENI.MI',
    holidayCalendar: 'italian',
  },
  {
    country: 'SE',
    timezone: 'Europe/Stockholm',
    exchanges: 'Nasdaq Stockholm',
    currency: 'SEK',
    sessions: day('09:00', '17:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'ST', exchange: 'Nasdaq Stockholm', mic: 'XSTO' }],
    testSymbol: 'VOLV-B.ST',
    holidayCalendar: 'swedish',
  },
  {
    country: 'NO',
    timezone: 'Europe/Oslo',
    exchanges: 'Oslo Børs',
    currency: 'NOK',
    sessions: day('09:00', '16:20'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'OL', exchange: 'Oslo Børs', mic: 'XOSL' }],
    testSymbol: 'EQNR.OL',
    holidayCalendar: 'norwegian',
  },
  {
    country: 'DK',
    timezone: 'Europe/Copenhagen',
    exchanges: 'Nasdaq Copenhagen',
    currency: 'DKK',
    sessions: day('09:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'CO', exchange: 'Nasdaq Copenhagen', mic: 'XCSE' }],
    testSymbol: 'NOVO-B.CO',
    holidayCalendar: 'danish',
  },
  {
    country: 'FI',
    timezone: 'Europe/Helsinki',
    exchanges: 'Nasdaq Helsinki',
    currency: 'EUR',
    sessions: day('10:00', '18:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'HE', exchange: 'Nasdaq Helsinki', mic: 'XHEL' }],
    testSymbol: 'NOKIA.HE',
    holidayCalendar: 'finnish',
  },
  {
    country: 'PL',
    timezone: 'Europe/Warsaw',
    exchanges: 'GPW',
    currency: 'PLN',
    sessions: day('09:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'WA', exchange: 'GPW', mic: 'XWAR' }],
    testSymbol: 'PKO.WA',
    holidayCalendar: 'polish',
  },
  {
    country: 'TR',
    timezone: 'Europe/Istanbul',
    exchanges: 'Borsa Istanbul',
    currency: 'TRY',
    sessions: day('10:00', '18:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'IS', exchange: 'Borsa Istanbul', mic: 'XIST' }],
    testSymbol: 'THYAO.IS',
    holidayCalendar: 'turkish',
  },
  {
    country: 'NG',
    timezone: 'Africa/Lagos',
    exchanges: 'NGX',
    currency: 'NGN',
    sessions: day('10:00', '14:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'LG', exchange: 'NGX', mic: 'XNSA' }],
    testSymbol: 'DANGCEM.LG',
    holidayCalendar: 'ng',
  },
  {
    country: 'ZA',
    timezone: 'Africa/Johannesburg',
    exchanges: 'JSE',
    currency: 'ZAR',
    sessions: day('09:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'JO', exchange: 'JSE', mic: 'XJSE' }],
    testSymbol: 'NPN.JO',
    holidayCalendar: 'sa',
  },
  {
    country: 'EG',
    timezone: 'Africa/Cairo',
    exchanges: 'EGX',
    currency: 'EGP',
    sessions: day('10:00', '14:30'),
    weekdays: SUN_THU,
    suffixes: [{ suffix: 'CA', exchange: 'EGX', mic: 'XCAI' }],
    testSymbol: 'COMI.CA',
    holidayCalendar: 'eg',
  },
  {
    country: 'IL',
    timezone: 'Asia/Jerusalem',
    exchanges: 'TASE',
    currency: 'ILS',
    sessions: day('09:59', '17:25'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'TA', exchange: 'TASE', mic: 'XTAE' }],
    testSymbol: 'TEVA.TA',
    holidayCalendar: 'jewish',
  },
  {
    country: 'SA',
    timezone: 'Asia/Riyadh',
    exchanges: 'Tadawul',
    currency: 'SAR',
    sessions: day('10:00', '15:00'),
    weekdays: SUN_THU,
    suffixes: [{ suffix: 'SR', exchange: 'Tadawul', mic: 'XSAU' }],
    testSymbol: '2222.SR',
    holidayCalendar: 'saudiarabian',
  },
  {
    country: 'AE',
    timezone: 'Asia/Dubai',
    exchanges: 'DFM, ADX',
    currency: 'AED',
    sessions: day('10:00', '15:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'AE', exchange: 'DFM', mic: 'XDFM' }],
    testSymbol: 'EMAAR.AE',
    holidayCalendar: 'ae',
  },
  {
    country: 'IN',
    timezone: 'Asia/Kolkata',
    exchanges: 'NSE, BSE',
    currency: 'INR',
    sessions: day('09:15', '15:30'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'NS', exchange: 'NSE', mic: 'XNSE' },
      { suffix: 'BO', exchange: 'BSE', mic: 'XBOM' },
    ],
    testSymbol: 'RELIANCE.NS',
    holidayCalendar: 'indian',
  },
  {
    country: 'TH',
    timezone: 'Asia/Bangkok',
    exchanges: 'SET',
    currency: 'THB',
    sessions: split('10:00', '12:30', '14:30', '16:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'BK', exchange: 'SET', mic: 'XBKK' }],
    testSymbol: 'PTT.BK',
    holidayCalendar: 'th',
  },
  {
    country: 'ID',
    timezone: 'Asia/Jakarta',
    exchanges: 'IDX',
    currency: 'IDR',
    sessions: split('09:00', '12:00', '13:30', '15:50'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'JK', exchange: 'IDX', mic: 'XIDX' }],
    testSymbol: 'BBCA.JK',
    holidayCalendar: 'indonesian',
  },
  {
    country: 'VN',
    timezone: 'Asia/Ho_Chi_Minh',
    exchanges: 'HOSE',
    currency: 'VND',
    sessions: split('09:00', '11:30', '13:00', '14:45'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'VN', exchange: 'HOSE', mic: 'XSTC' }],
    testSymbol: 'VNM.VN',
    holidayCalendar: 'vietnamese',
  },
  {
    country: 'SG',
    timezone: 'Asia/Singapore',
    exchanges: 'SGX',
    currency: 'SGD',
    sessions: split('09:00', '12:00', '13:00', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'SI', exchange: 'SGX', mic: 'XSES' }],
    testSymbol: 'D05.SI',
    holidayCalendar: 'singapore',
  },
  {
    country: 'MY',
    timezone: 'Asia/Kuala_Lumpur',
    exchanges: 'Bursa Malaysia',
    currency: 'MYR',
    sessions: split('09:00', '12:30', '14:30', '17:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'KL', exchange: 'Bursa Malaysia', mic: 'XKLS' }],
    testSymbol: '1155.KL',
    holidayCalendar: 'malaysia',
  },
  {
    country: 'PH',
    timezone: 'Asia/Manila',
    exchanges: 'PSE',
    currency: 'PHP',
    sessions: split('09:30', '12:00', '13:00', '15:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'PS', exchange: 'PSE', mic: 'XPHS' }],
    testSymbol: 'SM.PS',
    holidayCalendar: 'philippines',
  },
  {
    country: 'HK',
    timezone: 'Asia/Hong_Kong',
    exchanges: 'HKEX',
    currency: 'HKD',
    sessions: split('09:30', '12:00', '13:00', '16:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'HK', exchange: 'HKEX', mic: 'XHKG' }],
    testSymbol: '0700.HK',
    holidayCalendar: 'hong_kong',
  },
  {
    country: 'CN',
    timezone: 'Asia/Shanghai',
    exchanges: 'SSE, SZSE',
    currency: 'CNY',
    sessions: split('09:30', '11:30', '13:00', '15:00'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'SS', exchange: 'SSE', mic: 'XSHG' },
      { suffix: 'SZ', exchange: 'SZSE', mic: 'XSHE' },
    ],
    testSymbol: '600519.SS',
    holidayCalendar: 'china',
  },
  {
    country: 'TW',
    timezone: 'Asia/Taipei',
    exchanges: 'TWSE, TPEx',
    currency: 'TWD',
    sessions: day('09:00', '13:30'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'TW', exchange: 'TWSE', mic: 'XTAI' },
      { suffix: 'TWO', exchange: 'TPEx', mic: 'ROCO' },
    ],
    testSymbol: '2330.TW',
    holidayCalendar: 'taiwan',
  },
  {
    country: 'KR',
    timezone: 'Asia/Seoul',
    exchanges: 'KRX',
    currency: 'KRW',
    sessions: day('09:00', '15:30'),
    weekdays: MON_FRI,
    suffixes: [
      { suffix: 'KS', exchange: 'KOSPI', mic: 'XKRX' },
      { suffix: 'KQ', exchange: 'KOSDAQ', mic: 'XKOS' },
    ],
    testSymbol: '005930.KS',
    holidayCalendar: 'south_korea',
  },
  {
    country: 'JP',
    timezone: 'Asia/Tokyo',
    exchanges: 'TSE',
    currency: 'JPY',
    sessions: split('09:00', '11:30', '12:30', '15:30'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'T', exchange: 'TSE', mic: 'XTKS' }],
    testSymbol: '7203.T',
    holidayCalendar: 'japanese',
  },
  {
    country: 'AU',
    timezone: 'Australia/Sydney',
    exchanges: 'ASX',
    currency: 'AUD',
    sessions: day('10:00', '16:00'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'AX', exchange: 'ASX', mic: 'XASX' }],
    testSymbol: 'BHP.AX',
    holidayCalendar: 'australian',
  },
  {
    country: 'NZ',
    timezone: 'Pacific/Auckland',
    exchanges: 'NZX',
    currency: 'NZD',
    sessions: day('10:00', '16:45'),
    weekdays: MON_FRI,
    suffixes: [{ suffix: 'NZ', exchange: 'NZX', mic: 'XNZE' }],
    testSymbol: 'FPH.NZ',
    holidayCalendar: 'new_zealand',
  },
];

export function catalogMarket(country: string | null | undefined): CatalogMarket | undefined {
  return country ? MARKET_CATALOG.find((m) => m.country === country) : undefined;
}

export function holidayCalendarUrl(country: string): string | null {
  const slug = catalogMarket(country)?.holidayCalendar;
  return slug
    ? `https://calendar.google.com/calendar/ical/en.${slug}%23holiday%40group.v.calendar.google.com/public/basic.ics`
    : null;
}
